services:
  search.request.service:
    class: Search\Request\SearchRequest
    public: true
    arguments:
      - '@request_stack'

  search.request.param_converter:
    class: Search\ParamConverter\SearchRequestParamConverter
    arguments:
      - '@search.request.service'
    public: false
    tags:
      - { name: request.param_converter, converter: search_request }

